#Requires AutoHotkey v2.0
#SingleInstance Off

; Regenerate the built-in Chinese catalog without depending on the generated module.
try {
    GenerateLocaleFallback()
} catch as err {
    FileAppend("Uncaught exception: " . err.Message . "`n  at " . err.What . "`n  " . err.Line
        . "`nStack:`n" . err.Stack . "`n", "*")
    ExitApp(1)
}

GenerateLocaleFallback() {
    local root := A_ScriptDir . "\..", source, header, output, section := ""
    local line, match, key, seen := Map(), file
    seen.CaseSense := "On"
    source := FileRead(root . "\locales\zh-CN.ini", "UTF-8")
    header := StrSplit(FileRead(root . "\Lib\RabbitI18n.ahk", "UTF-8"), "#Include")[1]
    output := RTrim(StrReplace(header, "`r`n", "`n"), " `t`r`n") . "`n`n"
        . "; Generated by scripts/generate_locale_fallback.ahk. Do not edit by hand.`n"
        . "class RabbitLocaleFallback {`n    static Create() {`n        local catalog := Map()`n"
        . '        catalog.CaseSense := "On"' . "`n"
    for line in StrSplit(source, "`n", "`r") {
        line := Trim(line)
        if !line || SubStr(line, 1, 1) = ";" {
            continue
        }
        if RegExMatch(line, "^\[([a-zA-Z0-9_]+)\]$", &match) {
            section := match[1]
        } else if section && RegExMatch(line, "^([a-zA-Z0-9_]+)=(.*)$", &match) {
            key := section . "." . match[1]
            if seen.Has(key) {
                throw Error("Duplicate translation key: " . key)
            }
            seen[key] := true
            output .= "        catalog[" . LocaleAhkString(key) . "] := " . LocaleAhkString(match[2]) . "`n"
        } else {
            throw Error("Invalid translation line: " . line)
        }
    }
    if !seen.Count {
        throw Error("The Chinese translation catalog is empty.")
    }
    output .= "        return catalog`n    }`n}`n"
    ; Finish validation before opening the destination for replacement.
    file := FileOpen(root . "\Lib\RabbitLocaleFallback.ahk", "w", "UTF-8-RAW")
    try {
        file.Write(output)
    } finally {
        file.Close()
    }
    FileAppend("Generated " . seen.Count . " fallback entries.`n", "*")
}

LocaleAhkString(value) {
    local decoded := "", index := 1, char, escaped
    while index <= StrLen(value) {
        char := SubStr(value, index++, 1)
        if char = "\" && index <= StrLen(value) {
            escaped := SubStr(value, index++, 1)
            switch escaped {
                case "n": decoded .= "`n"
                case "r": decoded .= "`r"
                case "\": decoded .= "\"
                default: throw Error("Unknown translation escape: \" . escaped)
            }
        } else {
            decoded .= char
        }
    }
    decoded := StrReplace(decoded, Chr(96), Chr(96) . Chr(96))
    decoded := StrReplace(decoded, Chr(34), Chr(96) . Chr(34))
    decoded := StrReplace(decoded, "`r", "``r")
    decoded := StrReplace(decoded, "`n", "``n")
    return Chr(34) . decoded . Chr(34)
}
