"""Regenerate the built-in Chinese catalog after editing locales/zh-CN.ini."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

def ahk_string(value):
    value = re.sub(r"\\([nr\\])", lambda m: {"n": "\n", "r": "\r", "\\": "\\"}[m[1]], value)
    return '"' + value.replace('`', '``').replace('"', '`"').replace('\r', '`r').replace('\n', '`n') + '"'

def main():
    header = (ROOT / "Lib/RabbitI18n.ahk").read_text(encoding="utf-8-sig").split("#Include")[0]
    lines = [header.rstrip(), "", "; Generated by scripts/generate_locale_fallback.py. Do not edit by hand.",
             "class RabbitLocaleFallback {", "    static Create() {", "        local catalog := Map()",
             '        catalog.CaseSense := "On"']
    section = ""
    seen = set()
    for raw in (ROOT / "locales/zh-CN.ini").read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        key, value = line.split("=", 1)
        full_key = section + "." + key
        if full_key in seen:
            raise ValueError("Duplicate key: " + full_key)
        seen.add(full_key)
        lines.append(f"        catalog[{ahk_string(full_key)}] := {ahk_string(value)}")
    lines.extend(["        return catalog", "    }", "}", ""])
    (ROOT / "Lib/RabbitLocaleFallback.ahk").write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    main()
